# Generated by Django 4.1 on 2024-01-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Embedding模型名称', max_length=40, verbose_name='Embedding模型名称')),
                ('step', models.IntegerField(help_text='Embedding模型步长', null=True, verbose_name='Embedding模型步长')),
                ('sd_checkpoint', models.CharField(help_text='SD模型哈希值', max_length=40, null=True, verbose_name='SD模型哈希值')),
                ('sd_checkpoint_name', models.CharField(help_text='SD模型名称', max_length=40, null=True, verbose_name='SD模型名称')),
                ('shape', models.CharField(help_text='Embedding模型形状', max_length=40, null=True, verbose_name='Embedding模型形状')),
                ('vectors', models.IntegerField(help_text='Embedding模型向量数', null=True, verbose_name='Embedding模型向量数')),
                ('intro', models.TextField(blank=True, help_text='Embedding模型简介', null=True, verbose_name='Embedding模型简介')),
            ],
            options={
                'verbose_name': 'Embedding',
                'verbose_name_plural': 'Embedding',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Lora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Lora模型名称', max_length=40, verbose_name='Lora模型名称')),
                ('alias', models.CharField(blank=True, help_text='Lora模型别名', max_length=40, null=True, verbose_name='Lora模型别名')),
                ('path', models.CharField(blank=True, help_text='Lora模型路径', max_length=100, null=True, verbose_name='Lora模型路径')),
                ('metadata', models.JSONField(blank=True, help_text='Lora模型元数据', null=True, verbose_name='Lora模型元数据')),
                ('intro', models.TextField(blank=True, help_text='Lora模型简介', null=True, verbose_name='Lora模型简介')),
                ('cover', models.ImageField(blank=True, help_text='封面图片', null=True, upload_to='E:\\pythonProject\\pyBACKEND\\staticfiles\\cover/Lora/', verbose_name='封面图片')),
                ('show_name', models.CharField(blank=True, help_text='Lora模型展示名称', max_length=40, null=True, verbose_name='Lora模型展示名称')),
            ],
            options={
                'verbose_name': 'Lora',
                'verbose_name_plural': 'Lora',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Sampler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sampler名称', max_length=40, verbose_name='Sampler名称')),
                ('aliases', models.JSONField(blank=True, help_text='Sampler别名', null=True, verbose_name='Sampler别名')),
                ('options', models.JSONField(blank=True, help_text='Sampler选项', null=True, verbose_name='Sampler选项')),
            ],
            options={
                'verbose_name': 'Sampler',
                'verbose_name_plural': 'Sampler',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SDCheckPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='SD模型全称', max_length=50, verbose_name='SD模型全称')),
                ('model_name', models.CharField(help_text='SD模型名称', max_length=40, verbose_name='SD模型名称')),
                ('hash', models.CharField(help_text='SD模型哈希值', max_length=40, verbose_name='SD模型哈希值')),
                ('sha256', models.CharField(help_text='SD模型SHA256值', max_length=100, verbose_name='SD模型SHA256值')),
                ('filename', models.CharField(blank=True, help_text='SD模型文件名', max_length=100, null=True, verbose_name='SD模型文件名')),
                ('config', models.JSONField(blank=True, help_text='SD模型配置', null=True, verbose_name='SD模型配置')),
                ('intro', models.TextField(blank=True, help_text='SD模型简介', null=True, verbose_name='SD模型简介')),
                ('cover', models.ImageField(blank=True, help_text='封面图片', null=True, upload_to='E:\\pythonProject\\pyBACKEND\\staticfiles\\cover/SD/', verbose_name='封面图片')),
                ('show_name', models.CharField(blank=True, help_text='SD模型展示名称', max_length=40, null=True, verbose_name='SD模型展示名称')),
            ],
            options={
                'verbose_name': 'SD',
                'verbose_name_plural': 'SD',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Upscaler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Upscaler名称', max_length=40, verbose_name='Upscaler名称')),
                ('model_name', models.CharField(help_text='Upscaler模型名称', max_length=40, null=True, verbose_name='Upscaler模型名称')),
                ('model_path', models.CharField(help_text='Upscaler模型路径', max_length=100, null=True, verbose_name='Upscaler模型路径')),
                ('model_url', models.CharField(help_text='Upscaler模型URL', max_length=100, null=True, verbose_name='Upscaler模型URL')),
                ('scale', models.FloatField(help_text='Upscaler放大倍数', verbose_name='Upscaler放大倍数')),
            ],
            options={
                'verbose_name': 'Upscaler',
                'verbose_name_plural': 'Upscaler',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ThirdServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='第三方服务器名称', max_length=40, verbose_name='第三方服务器名称')),
                ('intro', models.TextField(blank=True, help_text='第三方服务器简介', null=True, verbose_name='第三方服务器简介')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('expire_time', models.DateTimeField(help_text='过期时间', verbose_name='过期时间')),
                ('is_alive', models.BooleanField(default=True, help_text='是否可用', verbose_name='是否可用')),
                ('domain', models.CharField(help_text='域名', max_length=40, verbose_name='域名')),
                ('port', models.IntegerField(help_text='端口', verbose_name='端口')),
                ('checkpoint', models.ForeignKey(help_text='SD模型', null=True, on_delete=django.db.models.deletion.SET_NULL, to='genImage.sdcheckpoint', verbose_name='SD模型')),
            ],
            options={
                'verbose_name': '第三方服务器',
                'verbose_name_plural': '第三方服务器',
                'ordering': ('-created_time',),
            },
        ),
    ]
