# Generated by Django 4.1 on 2024-01-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genImage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdserver',
            name='user_num',
            field=models.IntegerField(default=0, help_text='用户数量', null=True, verbose_name='用户数量'),
        ),
    ]
